// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlxln3Y1Hw-wvH2KlCYU18v0omqc_ajqk',
    appId: '1:763838342098:android:c7c14c48e61ae566ed1e0b',
    messagingSenderId: '763838342098',
    projectId: 'socialapp-d36b6',
    storageBucket: 'socialapp-d36b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8YjFyWmKmKacQub5Gf8NoRWydt6tMLcU',
    appId: '1:763838342098:ios:dfa82aa3b3776890ed1e0b',
    messagingSenderId: '763838342098',
    projectId: 'socialapp-d36b6',
    storageBucket: 'socialapp-d36b6.appspot.com',
    iosClientId: '763838342098-hbfdoji01qo2it1ro0105ukdgoi072qb.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
